const Access:{[key:number]:any}={    
    1:{ 
        complaints:true,
        customers:true,
        forms:true,
        installations:true,
        inquiries:true,
        stocks:true,
        master:true,
        download:true,
        allAccess:true
    },
    2:
    {
        complaints:false,
        customers:true,
        forms:true,
        installations:false,
        inquiries:false,
        stocks:false,
        master:false,
        customerrights:["view","createInstallation"]
    },
    3:{ 
        complaints:true,
        customers:true,
        forms:false,
        installations:true,
        inquiries:true,
        stocks:false,
        master:false,
        installationrights:["view","edit"],
        complaintrights:["view","edit"],
        customerrights:["edit","view"],
        inquiryrights:["edit","view"]
    }, 4:{ 
        complaints:true,
        customers:true,
        forms:true,
        installations:true,
        inquiries:true,
        stocks:true,
        master:false
    },
    5:{ 
        complaints:false,
        customers:true,
        forms:false,
        installations:false,
        inquiries:true,
        stocks:false,
        master:false,
        customerrights:["view"]
    },
    6:{ 
        complaints:false,
        customers:false,
        forms:false,
        installations:false,
        inquiries:false,
        stocks:true,
        master:false
    },
    7:{
        complaints:true,
        customers:false,
        forms:false,
        installations:true,
        inquiries:false,
        stocks:false,
        master:false,
        installationrights:["view","edit"],
        complaintrights:["view"],
    }
    
}

export default Access;